FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y \
        nginx \
        spawn-fcgi \
        libfcgi-dev \
        gcc \
        libc-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -r -s /usr/sbin/nologin laneryel && \
    chown -R laneryel:laneryel  /etc/nginx/nginx.conf; \
    chown -R laneryel:laneryel  /var/cache/nginx; \
    chown -R laneryel:laneryel  /var/run/nginx; \
    chown -R laneryel:laneryel  /run;\
    chown -R laneryel:laneryel  /var/lib/nginx; \
    chown -R laneryel:laneryel  /var/log/nginx;

WORKDIR /home/laneryel

COPY server/fcgi_hello.c .
RUN gcc fcgi_hello.c -lfcgi -o fcgi_hello.fcgi && \
    chmod +x fcgi_hello.fcgi

COPY nginx/nginx.conf /etc/nginx/nginx.conf

RUN chmod ug-s /usr/bin/passwd /bin/su /usr/bin/gpasswd /usr/bin/chfn /usr/bin/chsh \
    /usr/bin/chage /usr/bin/expiry /bin/mount /bin/umount /sbin/unix_chkpwd /usr/bin/newgrp || true

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD curl -f http://localhost/ || exit 1

USER laneryel

CMD ["/bin/sh", "-c", "spawn-fcgi -p 8080 ./fcgi_hello.fcgi && nginx -g 'daemon off;'"]
