version: "3"

services:
  fcgi:
    container_name: fcgi
    image: fcgi_server:improved

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - "./nginx_part6/nginx.conf:/etc/nginx/nginx.conf"
